## Global Configuration
global:
  kafka:
    bootstrapServers: "my-kafka.default.svc.cluster.local:9092"

## Kafka Configuration
replicaCount: 3

image:
  repository: bitnami/kafka
  tag: latest
  pullPolicy: IfNotPresent

brokers:
  heapOpts: "-Xmx1024m -Xms512m"


service:
  type: LoadBalancer
  port: 9092

auth:
  clientProtocol: plaintext
  interBrokerProtocol: plaintext
  saslMechanisms: scram-sha-256


topics:
  - name: hello-topic
    partitions: 1
    replicationFactor: 1
    # Add any other topic-level configurations you need here
  - name: error-topic
    partitions: 1
    replicationFactor: 1
    # Add any other topic-level configurations you need here
users:
  - name: kafkauser
    password: p@ssvv0rd
    acls:
      - resourceType: topic
        resourceName: hello-topic
        patternType: literal
        host: "*"
        operation: write
        permissionType: allow
      - resourceType: topic
        resourceName: error-topic
        patternType: literal
        host: "*"
        operation: write
        permissionType: allow
