## Global Configuration
global:
  kafka:
    bootstrapServers: "my-kafka.default.svc.cluster.local:9092"

## Kafka Configuration
replicaCount: 3

image:
  repository: bitnami/kafka
  tag: latest
  pullPolicy: IfNotPresent

brokers:
  heapOpts: "-Xmx1024m -Xms512m"


service:
  type: LoadBalancer
  port: 9092

topics:
  - name: hello-topic
    partitions: 1
    replicationFactor: 1
  - name: error-topic
    partitions: 1
    replicationFactor: 1

auth:
  clientProtocol: sasl
  interBrokerProtocol: sasl
  saslMechanisms: scram-sha-256
  jaas:
    clientUser: user1
    clientPassword: $(kubectl get secret my-kafka-user-passwords --namespace default -o jsonpath='{.data.client-passwords}' | base64 -d | cut -d , -f 1)"

