## Global Configuration
global:
  kafka:
    bootstrapServers: "my-kafka.default.svc.cluster.local:9092"

## Kafka Configuration
replicaCount: 3

image:
  repository: bitnami/kafka
  tag: latest
  pullPolicy: IfNotPresent

brokers:
  heapOpts: "-Xmx1024m -Xms512m"

#auth:
  #clientProtocol: sasl
  #interBrokerProtocol: sasl
  #saslMechanisms: SCRAM-SHA-256
  #jaas:
   # clientUser: user1
  #  clientPassword: KAFKA_PASSWORD  # этот пароль будет заменен на значение из Secret
 # rbac:
#    create: true

service:
  type: LoadBalancer
  port: 9092

topics:
  - name: hello-topic
    partitions: 1
    replicationFactor: 1
  - name: error-topic
    partitions: 1
    replicationFactor: 1
