clusterName: "elasticsearch"
nodeGroup: "master"

# Задайте количество реплик на 1 для однонодового кластера
replicas: 1

minimumMasterNodes: 1

esJavaOpts: "-Xmx128m -Xms128m"

resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "1000m"
    memory: "512M"

volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "standard"
  resources:
    requests:
      storage: 1Gi
